ALTER TABLE "user" ADD COLUMN "role" TEXT NOT NULL DEFAULT 'user';
ALTER TABLE "user" ADD COLUMN "isPublic" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "user" ADD COLUMN "showEmail" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "user" ADD COLUMN "showPosts" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "user" ADD COLUMN "showProfile" INTEGER NOT NULL DEFAULT 1;
