import { createSchema } from "zod-openapi";
import { z } from "zod";
const lifecycleProperties = { status: z.enum(["draft", "published"]).optional(), visibility: z.enum(["public", "unlisted", "private"]).optional(), scheduledAt: z.iso.datetime().nullable().optional(), contentWarning: z.string().max(500).nullable().optional() };
const originalPostProperties = { originalCreator: z.string().min(1).max(500).nullable().optional(), originalCreatedAt: z.iso.datetime().nullable().optional() };
const contentProperties = { contentType: z.enum(["image", "text"]).optional(), textContent: z.string().min(1).max(100000).nullable().optional() };
const permalinkProperties = { permalinkPattern: z.enum(["user", "posts"]).optional(), permalinkIdType: z.enum(["normalizedTitle", "internalId", "creationDate", "custom"]).optional(), customPostId: z.string().min(1).max(200).nullable().optional() };
export const postCreateInput = z.object({ title: z.string().min(1).max(500), ...contentProperties, description: z.string().max(10000).optional(), caption: z.string().max(10000).optional(), sourceUrl: z.string().max(4096).optional(), ...originalPostProperties, ...permalinkProperties, allowDownload: z.boolean().optional(), ...lifecycleProperties, tags: z.array(z.string().min(1).max(100)).max(100).optional(), categoryId: z.string().min(1).nullable().optional(), uploadIds: z.array(z.string().min(1)).max(100).optional() }).meta({ description: "Fields accepted when creating a post." });
export const postUpdateInput = z.object({ title: z.string().min(1).max(500).optional(), ...contentProperties, description: z.string().max(10000).nullable().optional(), caption: z.string().max(10000).nullable().optional(), allowDownload: z.boolean().optional(), sourceUrl: z.string().max(4096).nullable().optional(), ...originalPostProperties, ...permalinkProperties, categoryId: z.string().min(1).nullable().optional(), ...lifecycleProperties, tags: z.array(z.string().min(1).max(100)).max(100).optional() }).meta({ description: "One or more post fields to update. At least one field is required." });
export type PostCreateInput = z.infer<typeof postCreateInput>;
export type PostUpdateInput = z.infer<typeof postUpdateInput>;
const jsonSchema = (schema: Parameters<typeof createSchema>[0]): Record<string, unknown> => createSchema(schema).schema as Record<string, unknown>;
export const postCreateBodyJsonSchema = jsonSchema(postCreateInput);
export const postUpdateBodyJsonSchema = { ...jsonSchema(postUpdateInput), minProperties: 1 };
